/* GENERATED by scripts/optimise-images.mjs — do not edit.
   Maps each image base path to the widths that exist on disk. */

export const IMAGE_WIDTHS: Record<string, number[]> = {
  '/Sections/HOMES1': [640, 960, 1280, 1536],
  '/hero/H1': [640, 960, 1440],
  '/hero/H2': [640, 960, 1440],
  '/hero/H3': [640, 960, 1440],
  '/product/K1': [360, 480, 600, 702],
  '/product/K2': [360, 480, 600, 702, 900],
  '/product/S1': [360, 480, 600, 702],
  '/product/S2': [360, 480, 600, 702, 900],
  '/product/SK1': [360, 480, 600, 702],
  '/product/SK2': [360, 480, 600, 702, 900],
  '/product/WC1': [360, 480, 600, 702],
  '/product/WC2': [360, 480, 600, 702],
  '/product/WC3': [360, 480, 600, 702, 900],
};

/* Product photography grouped by category, from the filename prefix:
   S* sherwani  ·  K* kurta  ·  SK* shalwar kameez  ·  WC* waistcoat
   Sorted naturally, so S2 comes before S10. */
export const PRODUCT_IMAGES: Record<string, string[]> = {
  'kurta': ['/product/K1', '/product/K2'],
  'sherwani': ['/product/S1', '/product/S2'],
  'shalwar-kameez': ['/product/SK1', '/product/SK2'],
  'waistcoat': ['/product/WC1', '/product/WC2', '/product/WC3'],
};

/* Category tile art, from media/category/<slug>.<ext>. Optional — a
   category without one falls back to a product photograph. */
export const CATEGORY_IMAGES: Record<string, string> = {

};
